"""Made some changes to the skills column in employee table

Revision ID: 451602cc8af2
Revises: 8b6633ab5b56
Create Date: 2023-11-06 11:57:54.983864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451602cc8af2'
down_revision = '8b6633ab5b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
