"""Made some changes to the username column in employee table

Revision ID: 6c5909be8454
Revises: 451602cc8af2
Create Date: 2023-11-06 12:03:31.244796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5909be8454'
down_revision = '451602cc8af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
