"""Made some changes to the employees table

Revision ID: 831e7b207020
Revises: fa23346ae348
Create Date: 2023-11-06 11:51:58.235718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e7b207020'
down_revision = 'fa23346ae348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
