"""added columns

Revision ID: e2ad0ddd32b7
Revises: 19cb96b34883
Create Date: 2023-10-27 21:37:03.667080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ad0ddd32b7'
down_revision = '19cb96b34883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.drop_column('username')

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('user_name')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
