"""Made some changes to the jobs table

Revision ID: fa23346ae348
Revises: 0a3dd3dd6944
Create Date: 2023-11-06 11:13:31.587137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa23346ae348'
down_revision = '0a3dd3dd6944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employer_username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employer_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('employer_description')
        batch_op.drop_column('employer_username')
        batch_op.drop_column('employer_name')

    # ### end Alembic commands ###
